package Constants;

public class SiteConstants {
    //use "final" for constants in the framework for easier maintenance of texts/labels to be validated on the Front End. "final" type does not need inheritance for you to call it from other classes because it is a static value
    public static final String POPUP_X_HEADING = "Singapore Stories: Pathways";
    public static final String MASTHEAD_HEADING = "EXPERIENCE ART  YOUR  WAY";
    public static final String OPENING_HOURS = "Open daily, 10am – 7pm";
    public static final String OPENING_HOURS_HEADING = "Opening hours";
    public static final String VISITOR_INFORMATION_HEADING = "Visitor Information";
    public static final String MEMBERSHIP_LOGIN_BUTTON = "Log in";
    public static final String CART_PAGE_TITLE = "Cart | National Gallery Singapore";
    public static final String CART_PAGE_HEADING = "Your cart";
    public static final String MENU_ARIA_LABEL = "Main navigation";
    public static final String WHATS_ON_PAGE_HEADING = "What’s On";
    public static final String TODAY = "Today";
    public static final String TOURS = "Tours";
    public static final String A_GUIDE_FOR_FAMILIES = "A Guide for Families Visiting";
    public static final String COLLECTIONS_LANDING = "The World’s Largest";
    public static final String OUR_ARCHITECTURE_HISTORY = "Our Architecture & History";
    public static final String ARTWORK_DETAILS = "Artwork Details";
    public static final String INTRO_TO_ART = "Intro to Art";
    public static final String ART_AT_HOME_FOR_FAMILIES = "Art at Home for Families";
    public static final String AUDIO_TOURS_AND_GUIDES = "Audio Tours & Guides";
    public static final String ART_CONSERVATION = "Art Conservation";
    public static final String PUBLICATIONS = "Publications";
    public static final String PERSPECTIVES_MAGAZINE = "Perspectives Magazine";
    public static final String ONLINE_ART_COURSES = "Online Art Courses";
    public static final String CURATORIAL_RESEARCH = "Curatorial Research";
    public static final String GUIDED_TOURS = "Guided tours";
    public static final String SELF_GUIDED_TOURS = "Self-guided tours";
    public static final String ACCESSIBILITY_AT_THE_GALLERY = "Accessibility at the Gallery";
    public static final String ADMISSION_AND_TICKETING = "Admission & ticketing";
    public static final String DINE_AND_SHOP = "Dine & Shop";
    public static final String ROTUNDA_LIBRARY = "Rotunda Library & Archive";
    public static final String KEPPEL_CENTRE = "Keppel Centre for Art Education";
    public static final String SCHOOL_VISIT = "School Group Visits at the";
    public static final String BECOME_A_MEMBER = "Become a Gallery Member";
    public static final String SG_CULTURE_PASS = "SG Culture Pass";
    public static final String OUR_STORY = "Our Story";
    public static final String LEADERSHIP = "Leadership";
    public static final String OUR_AWARDS = "Our Awards";
    public static final String MEDIA_CENTRE = "Media Centre";
    public static final String ANNUAL_REPORTS = "Annual Reports";
    public static final String SUSTAINABILITY = "Sustainability";
    public static final String OUR_INITIATIVES = "Our Initiatives &";
    public static final String COMMUNITY_GROUP_VISITS= "Community Group Visits";
    public static final String CAREERS_AND_INTERNSHIPS = "Careers & Internships";
    public static final String VENUE_RENTAL = "Venue Rental";
    public static final String PHOTOSHOOTS = "Photoshoots & Filming";
    public static final String EXHIBITION = "Exhibition";
    public static final String BUSINESS_OPPORTUNITIES = "Business Opportunities";
    public static final String CONTACT = "Contact";
    public static final String WHISTLEBLOWING = "Whistleblowing";
    public static final String DONATE_AND_VOLUNTEER = "Donate & Volunteer";
    public static final String DONOR_PATRON_VOLUNTEER = "Donor, Patron, or Volunteer";
    public static final String MEDIA_PROFESSIONAL = "Media Professional";
    public static final String EVENT_ORGANISER = "Event Organiser";
    public static final String WHATS_ON_SELECT_AN_OPTION = "Select an option";

}
